/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdditionalFrames;

import MISC.FramesCall;
import java.util.Vector;

/**
 *
 * @author Varun
 */
public class ShowResult extends javax.swing.JFrame {

    /**
     * Creates new form ShowResult
     */
    private String Person;
    private String Problem;
    private String Stat;
    private String FeatureList;
    private String SelectedList;
    private String Report;
    private String AlgoParam;

    public ShowResult() {
        initComponents();
    }

    public void setPerson() {
        String person = InitiatorFrame.personData;
        Person = person;
    }

    public void setProblem(String res) {
        Problem = res;
    }

    public void setAlgoParam(String res) {
        AlgoParam = res;
    }

    public void setResStat(String res) {
        report.setText(res);
        Stat = res;
    }

    public void setResFeature(Vector holdFeatures, String res1[]) {
        String FList, SList;
        FList = " Total Features " + res1.length;

        for (int i = 0; i < res1.length; i++) {
            FList = FList + "\n " + i + " " + res1[i];
        }
        SList = "";
        for (int j = 0; j < holdFeatures.size(); j++) {
            String[] selectedFeatures = (String[]) holdFeatures.get(j);
            SList = SList + "\nFor output " + j + " selected features are " + selectedFeatures.length;
            for (int k = 0; k < selectedFeatures.length; k++) {
                SList = SList + "\n  " + k + " " + selectedFeatures[k];
            }//k models
        }//j outputs
        FeatureList = FList;
        SelectedList = SList;
    }

    public void setReport(String res) {
        Report = res;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        person_Info = new javax.swing.JButton();
        problem = new javax.swing.JButton();
        param = new javax.swing.JButton();
        completeFeature = new javax.swing.JButton();
        selectedFeature = new javax.swing.JButton();
        statisticsRes = new javax.swing.JButton();
        execution = new javax.swing.JButton();
        selection = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        report = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_Save = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        jMenuItem_Help = new javax.swing.JMenuItem();
        keyShortcut = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAbout = new javax.swing.JMenuItem();
        jMenuItemDeveloper = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        backM = new javax.swing.JMenuItem();
        statistics = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        trainingFile = new javax.swing.JMenuItem();
        testFile = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reports and Statistics");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Click to View "));

        person_Info.setText("Experiment  Counductor");
        person_Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                person_InfoActionPerformed(evt);
            }
        });

        problem.setText("The Problem ");
        problem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                problemActionPerformed(evt);
            }
        });

        param.setText("Parameter Settings");
        param.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paramActionPerformed(evt);
            }
        });

        completeFeature.setText("Total Features");
        completeFeature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeFeatureActionPerformed(evt);
            }
        });

        selectedFeature.setText("Selected Features");
        selectedFeature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedFeatureActionPerformed(evt);
            }
        });

        statisticsRes.setText("Performance Statistics");
        statisticsRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticsResActionPerformed(evt);
            }
        });

        execution.setText("Excecution Report");
        execution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executionActionPerformed(evt);
            }
        });

        selection.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        selection.setText("The Performance Statistics:");

        jButton2.setText("About Statistics");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(selection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(person_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(completeFeature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(problem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectedFeature, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(param, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(statisticsRes, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(execution, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(person_Info)
                    .addComponent(problem)
                    .addComponent(param)
                    .addComponent(jButton2))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(completeFeature)
                    .addComponent(selectedFeature)
                    .addComponent(statisticsRes)
                    .addComponent(execution))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selection)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Report"));

        jScrollPane2.setBorder(null);

        report.setColumns(20);
        report.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        report.setForeground(new java.awt.Color(0, 0, 51));
        report.setRows(5);
        jScrollPane2.setViewportView(report);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem_Save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_Save.setText("Save");
        jMenu1.add(jMenuItem_Save);

        exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        help.setText("Help");

        jMenuItem_Help.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_Help.setText("Help Contents");
        jMenuItem_Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_HelpActionPerformed(evt);
            }
        });
        help.add(jMenuItem_Help);

        keyShortcut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        keyShortcut.setText("Keyboard Shortcuts");
        keyShortcut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keyShortcutMouseClicked(evt);
            }
        });
        keyShortcut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyShortcutActionPerformed(evt);
            }
        });
        help.add(keyShortcut);
        help.add(jSeparator1);

        jMenuItemAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemAbout.setText("About");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        help.add(jMenuItemAbout);

        jMenuItemDeveloper.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemDeveloper.setText("Developers");
        jMenuItemDeveloper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeveloperActionPerformed(evt);
            }
        });
        help.add(jMenuItemDeveloper);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem6.setText("Version Info");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        help.add(jMenuItem6);
        help.add(jSeparator2);

        backM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        backM.setText("Start Page");
        backM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMActionPerformed(evt);
            }
        });
        backM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                backMKeyPressed(evt);
            }
        });
        help.add(backM);

        jMenuBar1.add(help);

        statistics.setText("About Statistical Formula ");
        statistics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statisticsMouseClicked(evt);
            }
        });
        jMenuBar1.add(statistics);

        jMenu3.setText("Open output file");

        trainingFile.setText("Training");
        trainingFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainingFileActionPerformed(evt);
            }
        });
        jMenu3.add(trainingFile);

        testFile.setText("Test");
        testFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testFileActionPerformed(evt);
            }
        });
        jMenu3.add(testFile);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem_HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_HelpActionPerformed
        FramesCall.helpCall();
    }//GEN-LAST:event_jMenuItem_HelpActionPerformed

    private void keyShortcutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keyShortcutMouseClicked

    }//GEN-LAST:event_keyShortcutMouseClicked

    private void keyShortcutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyShortcutActionPerformed
        FramesCall.keyShoutcut();
    }//GEN-LAST:event_keyShortcutActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        FramesCall.aboutTool();
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jMenuItemDeveloperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeveloperActionPerformed
        FramesCall.developers();
    }//GEN-LAST:event_jMenuItemDeveloperActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        FramesCall.versions();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void backMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMActionPerformed
        FramesCall.initiator();
        this.dispose();
    }//GEN-LAST:event_backMActionPerformed

    private void backMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_backMKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_backMKeyPressed

    private void trainingFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainingFileActionPerformed
        FramesCall.ensembleTrainCall();
    }//GEN-LAST:event_trainingFileActionPerformed

    private void testFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testFileActionPerformed
        FramesCall.ensembleTestCall();
    }//GEN-LAST:event_testFileActionPerformed

    private void statisticsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statisticsMouseClicked
        FramesCall.statisticsCall();
    }//GEN-LAST:event_statisticsMouseClicked

    private void person_InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_person_InfoActionPerformed
       report.setText(Person);
       selection.setText("The Person Information:");
    }//GEN-LAST:event_person_InfoActionPerformed

    private void completeFeatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeFeatureActionPerformed
        report.setText(FeatureList);
        selection.setText("The Complete List of the Features available in the Problem:");
    }//GEN-LAST:event_completeFeatureActionPerformed

    private void selectedFeatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedFeatureActionPerformed
        report.setText(SelectedList);
        selection.setText("The List of the Selected Features from the Modelling:");
    }//GEN-LAST:event_selectedFeatureActionPerformed

    private void problemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_problemActionPerformed
        report.setText(Problem);
        selection.setText("The Problem Used for the Modelling:");
    }//GEN-LAST:event_problemActionPerformed

    private void statisticsResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticsResActionPerformed
       report.setText(Stat);
       selection.setText("The Performance Statistics:");
    }//GEN-LAST:event_statisticsResActionPerformed

    private void executionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executionActionPerformed
        report.setText(Report);
        selection.setText("The Program Excecution History:");
    }//GEN-LAST:event_executionActionPerformed

    private void paramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paramActionPerformed
        report.setText(AlgoParam);
        selection.setText("The Parameter Setting Used for Modelling:");
    }//GEN-LAST:event_paramActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FramesCall.statisticsCall();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem backM;
    private javax.swing.JButton completeFeature;
    private javax.swing.JButton execution;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu help;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemDeveloper;
    private javax.swing.JMenuItem jMenuItem_Help;
    private javax.swing.JMenuItem jMenuItem_Save;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem keyShortcut;
    private javax.swing.JButton param;
    private javax.swing.JButton person_Info;
    private javax.swing.JButton problem;
    private javax.swing.JTextArea report;
    private javax.swing.JButton selectedFeature;
    private javax.swing.JLabel selection;
    private javax.swing.JMenu statistics;
    private javax.swing.JButton statisticsRes;
    private javax.swing.JMenuItem testFile;
    private javax.swing.JMenuItem trainingFile;
    // End of variables declaration//GEN-END:variables
}
